Fix performance issues geting ne
IntellectualSites/FastAsyncWorldEdit pull request #1027
Opened 2021-04-12 22:16 UTC by Aurelien30000

## Overview

This PR aims to fix a huge issue with thousands of history files saved on disk.
The same behavior has been copied out to CfiChangeSet, class that used the same behaviour to get the next file id.

**Fixes #887**

## Description

Firstly, I tried the suggested fix using ``java.nio`` package, that wasn't successful at all.
Then, I decided to simply cache these heavy values in Maps, and load the first value thanks to the old method, still needed with this implementation.

## Checklist

- [x] I included all information required in the sections above
- [x] I tested my changes and approved their functionality
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/1.16/CONTRIBUTING.md)

2021-04-12 22:28 UTC, NotMyFault requested changes

2021-04-12 22:28 UTC, NotMyFault commented on worldedit-core/src/main/java/com/boydti/fawe/object/changeset/CFIChangeSet.java
> +import java.util.*;
Don't use wildcard imports.

2021-04-13 10:31 UTC, NotMyFault approved these changes

2021-04-13 14:41 UTC, Aurelien30000 commented
Thanks to @SirYwell for the requested changes to improve and ensure safety of this fix!

2021-04-13 14:42 UTC, SirYwell approved these changes

2021-04-13 14:55 UTC, merged