Fix reading of tile entities with "id" instead of "Id" tag
IntellectualSites/FastAsyncWorldEdit pull request #1220
Opened 2021-08-09 11:05 UTC by Gerrygames

## Overview
If a schematic contains a tile entity with an "id" instead of an "Id" the previous code would delete the id. The changed code checks which one of the tags is set.

This schematic for example caused this exception:
https://i.imgur.com/qjrT6ut.png
http://paste.cytooxien.de/jowobiyile.bash

## Checklist

- [x] I included all information required in the sections above
- [x] I tested my changes and approved their functionality
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/main/CONTRIBUTING.md)

2021-08-09 11:08 UTC, dordsor21 commented
"Id" is the correct format based on the schematic format. https://github.com/SpongePowered/Schematic-Specification/blob/master/versions/schematic-2.md

If "id" is present, then the schematic is highly likely to have been created by someone that doesn't follow the format, and is therefore highly likely to be "corrupt".

2021-08-09 11:30 UTC, Gerrygames commented
But we/fawe uses id internally. So why should it not accept files with id? Also it did work fine in previous versions. And an obscure npe should not be expected behavior even with corrupted files. That's why I added the  requireTag.

2021-08-09 11:32 UTC, dordsor21 commented
> But we/fawe uses id internally. So why should it not accept files with id? Also it did work fine in previous versions. And an obscure npe should not be expected behavior even with corrupted files. That's why I added the requireTag.

Minecraft uses "id" internally, so so does FAWE/WE. The Sponge schematic format details using "Id", so that is used. If "id" is saved to a schematic by either WE or FAWE then something has gone wrong, and it is likely to be corrupt.

2021-08-09 11:33 UTC, Gerrygames commented
The file is not corrupt. It works perfectly fine with an old version of FAWE and with this fix.

2021-08-09 11:37 UTC, dordsor21 commented
> The file is not corrupt. It works perfectly fine with an old version of FAWE and with this fix.

FAWE used to write corrupt schematics by writing "id" rather than "Id" or omitting it altogether sometimes. This was corrected at the end of 2020

2021-08-09 11:39 UTC, Gerrygames commented
And those schematics are no longer supporter now? Nice solution.

2021-08-09 15:43 UTC, NotMyFault commented
> > The file is not corrupt. It works perfectly fine with an old version of FAWE and with this fix.
> 
> FAWE used to write corrupt schematics by writing "id" rather than "Id" or omitting it altogether sometimes. This was corrected at the end of 2020

Do you have an appx. duration in mind for how long that used to be a thing? Seeing that this is the first report after 8 months, I assume not for toolong or people simply redoing their schematics after half a year. Else we could consider some kind of legacy handing how we do it with TEs.

2021-08-17 01:01 UTC, MattBDev commented
@Gerrygames Was this tested loading the "broken" schematic? If so, did the schematic load successfully?


> > The file is not corrupt. It works perfectly fine with an old version of FAWE and with this fix.
> 
> FAWE used to write corrupt schematics by writing "id" rather than "Id" or omitting it altogether sometimes. This was corrected at the end of 2020

If there are still schematics out there that were written with the incorrect tag name then we should support loading them. However, we should notify people that these schematics are corrupted and need to be resaved (unless we do this automatically).

2021-08-23 20:48 UTC, dordsor21 requested changes
I've made a change that "supports" tile entities in "corrupt" positions, thus I suppose it's logical this PR should also be accepted. It would, however, also need to make the same change in the FastSchematicReader

2021-09-24 15:41 UTC, dordsor21 commented
Implemented in 6b5f21d67bfe6badd4d893fb58e2ece22e7bdcd8

2021-09-24 15:41 UTC, closed without merging