Add basic preloading
IntellectualSites/FastAsyncWorldEdit pull request #1221
Opened 2021-08-09 13:58 UTC by dordsor21

- Added to commands that use region selections (that don't then use a visitor that preloads itself)
- TODO: more advanced preloading based on iterations/directions/sizes (stack, paste, etc)
- TODO: consider adding chunk tickets to prevent chunk unloads (though paper's delay-chunk-unloads should be enough)
- TODO: allow chunk preloading with Spigot

2021-08-09 15:10 UTC, NotMyFault requested changes
I'm feeling a bit sorry for the many `Javadocs`, but adding documentation when adding new methods or modifying existing ones will (at least I believe so lol) be helpful for us, contributors or api users (whether they use it is a different topic), in the long run.

2021-08-09 15:10 UTC, NotMyFault commented on worldedit-core/src/main/java/com/sk89q/worldedit/function/visitor/DownwardVisitor.java
> +    public DownwardVisitor(Mask mask, RegionFunction function, int baseY, int depth, Extent extent) {
Javadocs

2021-08-09 15:10 UTC, NotMyFault commented on worldedit-core/src/main/java/com/sk89q/worldedit/function/visitor/LayerVisitor.java
> +    public LayerVisitor(FlatRegion flatRegion, int minY, int maxY, LayerFunction function) {
Javadocs

2021-08-09 15:10 UTC, NotMyFault commented on worldedit-core/src/main/java/com/sk89q/worldedit/function/visitor/NonRisingVisitor.java
> +    public NonRisingVisitor(Mask mask, RegionFunction function, int depth, Extent extent) {
Javadocs

2021-08-09 15:10 UTC, NotMyFault commented on worldedit-core/src/main/java/com/sk89q/worldedit/function/visitor/RecursiveVisitor.java
> +    public RecursiveVisitor(Mask mask, RegionFunction function, int maxDepth) {
Javadocs

2021-08-09 15:10 UTC, NotMyFault commented on worldedit-core/src/main/java/com/sk89q/worldedit/function/visitor/RecursiveVisitor.java
>       */
maxDepth & extent misses

2021-08-09 15:16 UTC, dordsor21 commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/SingleThreadQueueExtent.java
> +                chunkLoadSet.add(from.getX(), 0, from.getZ());
This is correct. We only need the X and Z because they represent the chunk coordinates. The y value has no relevance to loading a chunk

2021-08-09 15:27 UTC, dordsor21 commented on worldedit-core/src/main/java/com/sk89q/worldedit/function/operation/ForwardExtentCopy.java
> +            blockCopy = new RegionVisitor(region, copy, preloader);
? There's no alternative for this currently.

2021-08-09 15:54 UTC, NotMyFault requested changes

2021-08-09 15:54 UTC, NotMyFault commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/queue/implementation/SingleThreadQueueExtent.java
> +     * Define a region to be "preloaded" to the number of chunks provided by the queue.preload-chunk-count setting
Can use `{@link Settings.QUEUE#PRELOAD_CHUNK_COUNT}` here.

2021-08-09 15:55 UTC, NotMyFault commented
I got the following on shutdown https://paste.gg/p/anonymous/71cacb9742d441a986f1524313e96a0e

2021-08-09 17:46 UTC, NotMyFault approved these changes

2021-08-17 00:43 UTC, MattBDev commented on worldedit-core/src/main/java/com/sk89q/worldedit/function/operation/ForwardExtentCopy.java
> +            blockCopy = new RegionVisitor(region, copy, preloader);
Use of the deprecated constructor is fine, marking this as resolved.

2021-08-17 00:47 UTC, MattBDev approved these changes

2021-08-17 00:47 UTC, merged