Sort plugins on debugpaste
IntellectualSites/FastAsyncWorldEdit pull request #1429
Opened 2021-11-18 23:17 UTC by Owen1212055

## Overview

Resolves #1428

## Description

Replace plugins with a list that is sorted using the compareToIgnoreCase statement. (The plugins command uses the CASE_INSENSITIVE_ORDER comparator, which this method uses this same comparator) 

## Checklist

- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] I tested my changes and approved their functionality.
- [X] I ensured my changes do not break other parts of the code
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md)

2021-11-18 23:24 UTC, dordsor21 approved these changes
Fair enough aha

2021-11-18 23:32 UTC, NotMyFault approved these changes
LGTM, thanks for the contribution!

We may merge it in 24 hours if there is no negative feedback, as per the [merge process ](https://github.com/IntellectualSites/IntellectualSites/blob/main/docs/MAINTAINERS_CONTRIBUTORS.adoc#merge-process) documentation.

2021-11-19 07:40 UTC, SirYwell requested changes
Minor nitpick, looks good overall.

2021-11-19 07:40 UTC, SirYwell commented on worldedit-bukkit/src/main/java/com/fastasyncworldedit/bukkit/FaweBukkit.java
> +        plugins.sort((plugin1, plugin2) -> plugin1.getName().compareToIgnoreCase(plugin2.getName()));
```suggestion
        plugins.sort(Comparator.comparing(Plugin::getName));
```

2021-11-20 16:21 UTC, SirYwell approved these changes

2021-11-20 16:28 UTC, merged