Only call org.bukkit.World height methods if they're present (1.17+)
IntellectualSites/FastAsyncWorldEdit pull request #1551
Opened 2022-01-17 15:15 UTC by dordsor21

2022-01-17 15:24 UTC, NotMyFault commented on worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/BukkitWorld.java
> +    public static final boolean HAS_MIN_Y;
Missing Fawe annotations, but `HAS_3D_BIOMES` can stay private, no?

2022-01-18 14:25 UTC, NotMyFault approved these changes
Untested, due me not having such an old test setup atm, but looks good.

2022-01-19 13:41 UTC, NotMyFault commented
/rebase

2022-01-21 08:28 UTC, SirYwell requested changes
Wouldn't it make more sense to use the `getMinY()`|`getMaxY()` methods from the WE world? (or `getMinimumPoint().getY()`|`getMaximumPoint().getY()` from Extent if no world is present)

2022-01-22 12:27 UTC, dordsor21 commented
> Wouldn't it make more sense to use the `getMinY()`|`getMaxY()` methods from the WE world? (or `getMinimumPoint().getY()`|`getMaximumPoint().getY()` from Extent if no world is present)

Changing to a BukkitWorld for regen stuff would require wrapping or the method signatures to all be changes to accept BukkitWorlds. For that case it's far much efficient to just access the static field

2022-01-28 19:58 UTC, SirYwell approved these changes

2022-01-28 20:10 UTC, NotMyFault commented
This PR is ready to be merged, we will merge it in ~24 hours if there is no negative feedback, as documented by the [merge process](https://github.com/IntellectualSites/IntellectualSites/blob/main/docs/MAINTAINERS_CONTRIBUTORS.adoc#merge-process) documentation.

2022-01-29 12:12 UTC, merged