Fix //snapshot in 1.18 and re-implement biome/entity restoration
IntellectualSites/FastAsyncWorldEdit pull request #1620
Opened 2022-02-17 18:23 UTC by dordsor21

Fixes #1568

2022-02-18 15:00 UTC, NotMyFault requested changes
- `//restore -b` doesn't work https://paste.gg/p/anonymous/b8330f24c792454fa1704411076ea34e
- `//restore -e` does not restore armor stands

2022-02-18 15:00 UTC, NotMyFault commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/util/NbtUtils.java
> +     */
`@since`

2022-02-18 15:00 UTC, NotMyFault commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/util/NbtUtils.java
> +     */
`since todo`

2022-02-20 16:17 UTC, dordsor21 commented
Armourstand restoration works fine for me? Did you use `//restore -e`?

2022-02-20 16:32 UTC, NotMyFault commented
> Armourstand restoration works fine for me? Did you use `//restore -e`?

Yeah, do I need to do anything special to make it work? The items I put in the chest were restored fine.

2022-02-20 16:50 UTC, dordsor21 commented
other tthan //restore -e, no

2022-02-20 23:11 UTC, NotMyFault commented
https://streamable.com/a93mkp This is what I did to test entity restoring. Unless I'm mistaken, it _should_ work like that, no?

2022-02-20 23:28 UTC, dordsor21 commented
Seems to be a bug specifically with zipped backups

2022-02-21 00:00 UTC, NotMyFault approved these changes

2022-02-23 16:04 UTC, SirYwell approved these changes

2022-02-24 09:33 UTC, merged