Prevent unhinged tree generation by doing a sanity check on the block below/block of the tree placement
IntellectualSites/FastAsyncWorldEdit pull request #1811
Opened 2022-06-14 16:57 UTC by dordsor21

EngineHub/WorldEdit/issues#2008

2022-06-14 17:36 UTC, NotMyFault approved these changes

2022-06-16 10:08 UTC, SirYwell requested changes

2022-06-16 10:09 UTC, dordsor21 commented on worldedit-core/src/main/java/com/sk89q/worldedit/util/TreeGenerator.java
> +        public boolean canGenerateOn(BlockType type) {
I left it public as it could be a useful API method

2022-06-16 10:12 UTC, SirYwell approved these changes

2022-06-16 14:23 UTC, merged