Re-implement incremental schematic names in a folder
IntellectualSites/FastAsyncWorldEdit pull request #1833
Opened 2022-06-19 13:23 UTC by dordsor21

- Fixes #1545

2022-06-19 17:22 UTC, NotMyFault approved these changes

2022-06-19 17:22 UTC, NotMyFault commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
>          //FAWE end
That does no longer apply.

2022-06-22 08:33 UTC, SirYwell requested changes

2022-06-22 08:33 UTC, SirYwell commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/SchematicCommands.java
> +        if (i == -1 && f.getName().isEmpty() || i == 0) {
Can a file name be emtpy?
We're checking both `i == - 1` and the empty name two times, maybe it can be extracted into variables for readability.

2022-06-23 07:37 UTC, SirYwell approved these changes

2022-06-23 08:23 UTC, merged