fix: Add blocked blocks to the correct set
IntellectualSites/FastAsyncWorldEdit pull request #1975
Opened 2022-10-08 09:51 UTC by dordsor21

2022-10-09 17:27 UTC, SirYwell requested changes

2022-10-09 17:27 UTC, SirYwell commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/DisallowedBlocksExtent.java
> +                if ((block = blocks[i]) == BlockTypesCache.ReservedIDs.__RESERVED__) {
I'd prefer to avoid this assignment expression and initialize `block` directly instead

2022-10-10 18:14 UTC, SirYwell approved these changes

2022-10-13 17:21 UTC, NotMyFault approved these changes

2022-10-13 17:21 UTC, merged