Add paper 1.19.4 support
IntellectualSites/FastAsyncWorldEdit pull request #2152
Opened 2023-03-15 09:19 UTC by TheMeinerLP

## Overview
Yersterday paper released the wip state of 1.19.4. I pre-compiled already and ported the code to 1.19.4 
A pre-compiled 1.19.4 paper version comes with fawe this following error:
https://paste.gg/p/anonymous/27517a721e5c41069efc1dfa82e470f8
 

## Description
Paperweight 1.19.4 port and support

## Submitter Checklist
- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

2023-03-15 09:27 UTC, TheMeinerLP commented
**Important** Its use a local m2 for compiling in very early stage of paper

2023-03-15 23:16 UTC, NotMyFault commented
Thanks for the initial work. I went ahead and replaced your local paperweight version with the official release.

2023-03-17 20:36 UTC, AnttiMK requested changes
Tried to build the branch for testing, but stumbled upon some compilation errors that might need addressing.

2023-03-17 20:36 UTC, AnttiMK commented on worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_19_R3/PaperweightAdapter.java
> +public final class PaperweightAdapter implements BukkitImplAdapter {
```suggestion
public final class PaperweightAdapter implements BukkitImplAdapter<net.minecraft.nbt.Tag> {
```
Missing type parameter

2023-03-17 20:36 UTC, AnttiMK commented on worldedit-bukkit/adapters/adapter-1_19_4/src/main/java/com/sk89q/worldedit/bukkit/adapter/impl/fawe/v1_19_R3/regen/PaperweightRegen.java
> +import com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R2.PaperweightGetBlocks;
```suggestion
import com.sk89q.worldedit.bukkit.adapter.impl.fawe.v1_19_R3.PaperweightGetBlocks;
```
Invalid import

2023-03-17 21:11 UTC, NotMyFault commented
Hey,

thanks for your PR and your contributions @AnttiMK. I created a branch based on your work in this repository: https://github.com/IntellectualSites/FastAsyncWorldEdit/pull/2154

@TheMeinerLP you forked FAWE to an organization instead of your personal account. Hence I'm unable to push anything to your organization.

2023-03-17 21:11 UTC, closed without merging

2023-03-17 21:29 UTC, TheMeinerLP commented
Thanks for the tip. How can i change that for future requests ?

2023-03-17 21:31 UTC, NotMyFault commented
> Thanks for the tip. How can i change that for future requests ?

If you are on https://github.com/IntellectualSites/FastAsyncWorldEdit/fork, select a repository owner on the dropdown list, that is not an organization.

2023-03-17 21:36 UTC, TheMeinerLP commented
And with organization is not working ?

2023-03-17 21:37 UTC, NotMyFault commented
Not in a way maintainers can contribute back. Hence you don’t contribute from organisations directly, rather have it on a personal account.

> On 17. Mar 2023, at 22:36, Phillipp Glanz ***@***.***> wrote:
> 
> 
> And with organization is not working ?
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/IntellectualSites/FastAsyncWorldEdit/pull/2152#issuecomment-1474425173>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/ADGDOVNSQMF2JU3GAMYCIZTW4TKPDANCNFSM6AAAAAAV3QXQPI>.
> You are receiving this because you modified the open/close state.
>