feat: improvements to clipboard on disk
IntellectualSites/FastAsyncWorldEdit pull request #2162
Opened 2023-03-25 13:10 UTC by dordsor21

- close clipboard on instantiation failure
 - set canHaveBiomes when loading clipboard from disk (only possible cause I can find for #2151 ..?)
 - check file length and give more appropriate error if it exceeds maximum. Fixes #2151 I guess?
 - set byteBuffer to null before invoking cleaning. Addresses #1985

2023-03-25 14:47 UTC, SirYwell requested changes

2023-03-25 14:47 UTC, SirYwell commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java
> +            canHaveBiomes = headerSize + biomeLength < Integer.MAX_VALUE;
This looks suspicious, `canHaveBiomes` is only false if `headerSize + biomeLength == Integer.MAX_VALUE`? I assume you want an overflow check there?

2023-03-25 14:47 UTC, SirYwell commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java
> +            long fileLength = (long) getVolume() << 1 + (long) headerSize;
This is most likely wrong as + has a higher precedence than <<, while + has a lower precedence than *

2023-03-26 20:05 UTC, SirYwell approved these changes
I can't really test for any of these but code-wise it looks good now

2023-03-29 22:13 UTC, NotMyFault approved these changes

2023-03-29 22:13 UTC, merged