Improve testability by adding more versions of runPaper to the build scripts
IntellectualSites/FastAsyncWorldEdit pull request #2172
Opened 2023-04-06 17:03 UTC by TheMeinerLP

## Overview
Help our developer to test FAWE across different minecraft versions
## Description
Help our developer to test FAWE across different minecraft versions

## Submitter Checklist

- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

2023-04-06 17:38 UTC, SirYwell requested changes

2023-04-06 17:38 UTC, SirYwell commented on build.gradle.kts
> +        register<xyz.jpenilla.runpaper.task.RunServer>("runServer-$it") {
It's fine to import this I guess

2023-04-06 17:39 UTC, TheMeinerLP commented on build.gradle.kts
> +        register<xyz.jpenilla.runpaper.task.RunServer>("runServer-$it") {
I will correct that

2023-04-07 06:40 UTC, SirYwell approved these changes
Looks good.

2023-04-07 13:09 UTC, NotMyFault approved these changes

2023-04-07 13:10 UTC, merged