Bugfix/1994
IntellectualSites/FastAsyncWorldEdit pull request #2193
Opened 2023-04-28 22:22 UTC by TheMeinerLP

## Overview

Fixes #1994 

## Description
Thanks to @GiantTreeLP to help me to identify the issue with the console command sender from fawe/worldedit.

## Submitter Checklist

- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

2023-04-29 18:02 UTC, PierreSchwang requested changes
Looks good otherwise I'd say

2023-04-29 18:02 UTC, PierreSchwang commented on worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java
> +    // Fawe stop
`stop` -> `end`

2023-04-29 18:02 UTC, PierreSchwang commented on worldedit-bukkit/src/main/java/com/sk89q/worldedit/bukkit/WorldEditPlugin.java
> +//575AFD72384E9CF4B59175B4502E5637
?

2023-04-29 18:54 UTC, SirYwell approved these changes

2023-04-30 15:36 UTC, dordsor21 approved these changes

2023-05-11 19:59 UTC, MattBDev approved these changes

2023-05-12 11:12 UTC, merged