Add mangrove tree type
IntellectualSites/FastAsyncWorldEdit pull request #2198
Opened 2023-04-30 11:58 UTC by TheMeinerLP

## Overview
Fixes #2197 

## Description
Add some debug messages for exceptions. Also add mangrove as a tree type

## Submitter Checklist

- [X] Make sure you are opening from a topic branch (**/feature/fix/docs/ branch** (right side)) and not your main branch.
- [X] Ensure that the pull request title represents the desired changelog entry.
- [X] New public fields and methods are annotated with `@since TODO`.
- [X] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/.github/blob/main/CONTRIBUTING.md).

2023-05-01 08:04 UTC, NotMyFault commented
Tests are failing.

2023-05-01 09:25 UTC, SirYwell requested changes
Catching unchecked exceptions should be a last resort workaround if we can't control the code. In this case, however, it looks like we can properly deal with it instead of catching exceptions?

2023-05-01 09:30 UTC, TheMeinerLP commented
> Catching unchecked exceptions should be a last resort workaround if we can't control the code. In this case, however, it looks like we can properly deal with it instead of catching exceptions?

There is currently no other way for handle thats type. 
I tried to check it before we register that tree type. But everytime it fails.
Now this solution is the friendliest one for every user of fawe.

2023-05-01 09:33 UTC, SirYwell commented
The NPE catches can clearly be replaced with null checks earlier. Registering the mapping can be guarded by a version check.

2023-05-01 09:33 UTC, TheMeinerLP commented
> The NPE catches can clearly be replaced with null checks earlier. Registering the mapping can be guarded by a version check.

The NPE comes from Bukkit it self. We can't handle it simple null checks

2023-05-01 09:36 UTC, SirYwell commented
I assume the NPE comes from `TreeType bukkitType = BukkitWorld.toBukkitTreeType(treeType);` being null? If so, we can simply return directly there

2023-05-01 09:38 UTC, TheMeinerLP commented
> I assume the NPE comes from `TreeType bukkitType = BukkitWorld.toBukkitTreeType(treeType);` being null? If so, we can simply return directly there

The NPE comes from internal of Bukkit not from our code. `bukkitWorld.generateTree(<PLACEHOLDER>, type)` throws a exception when we give over the tree type

2023-05-01 09:40 UTC, SirYwell commented
Which type? It will be null if the type doesn't exist on that version -> NPE

2023-05-01 09:50 UTC, TheMeinerLP commented
> Which type? It will be null if the type doesn't exist on that version -> NPE

I will try to handle it with null check and add a comment why.
Also i will add the debug again

2023-05-04 16:32 UTC, NotMyFault reviewed
This should really be in upstream.

2023-05-04 16:32 UTC, TheMeinerLP commented
I can do that 😄

2023-05-13 00:26 UTC, MattBDev requested changes
I am requesting some changes since this will be a commit will have to PR to EngineHub/WorldEdit. 
In addition to the recommendations I commented on, I would also like to see Tall Mangrove tree's added to this PR before I approve.

2023-05-13 00:26 UTC, MattBDev commented on worldedit-core/src/main/java/com/sk89q/worldedit/util/TreeGenerator.java
> +        MANGROVE("Mangrove", "mangrove"),
```suggestion
        MANGROVE("Mangrove tree", "mangrove"),
```

2023-06-19 20:47 UTC, NotMyFault commented
Upstreamed by dordsor, due to lack of action by the PR creator.

2023-06-19 20:47 UTC, closed without merging