feat: improve fawe mask handling
IntellectualSites/FastAsyncWorldEdit pull request #2312
Opened 2023-06-18 17:56 UTC by dordsor21

- Actually cache masks, even if the player has left the region
 - Fix P2 isValid test for single plots
 - Fixes #1946

2023-06-18 17:56 UTC, dordsor21 commented
Thoughts on the possibility of a memory leak with this?

2023-06-27 09:04 UTC, NotMyFault approved these changes

2023-06-27 10:22 UTC, SirYwell requested changes

2023-06-27 10:22 UTC, SirYwell commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/regions/FaweMask.java
> +        return isValid(player, type, notify);
This looks unintended

2023-06-27 16:53 UTC, SirYwell approved these changes

2023-06-28 08:24 UTC, merged