Implement async notify queue that submits to a KeyQueuedExecutorService
IntellectualSites/FastAsyncWorldEdit pull request #2334
Opened 2023-07-05 18:30 UTC by dordsor21

- Fixes #2332

2023-07-19 14:21 UTC, SirYwell requested changes

2023-07-19 14:21 UTC, SirYwell commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/util/task/AsyncNotifyKeyedQueue.java
> +    private boolean closed;
This should be `volatile` I guess?

2023-07-19 15:03 UTC, SirYwell approved these changes

2023-07-20 15:57 UTC, NotMyFault approved these changes

2023-07-20 15:58 UTC, merged