feat: provide some information upon OverlappingFileLockException
IntellectualSites/FastAsyncWorldEdit pull request #2341
Opened 2023-07-07 12:01 UTC by dordsor21

2023-07-07 14:11 UTC, SirYwell requested changes

2023-07-07 14:11 UTC, SirYwell commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java
> +                            "Cannot lock clipboard file {} acquired by thread {}, {}s ago",
The actual state of the lock would be interesting here as well imo

2023-07-07 16:11 UTC, dordsor21 commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/extent/clipboard/DiskOptimizedClipboard.java
> +    private static final Map<String, LockHolder> LOCK_HOLDER_CACHE = new HashMap<>();
Ah yeah probably

2023-07-08 15:00 UTC, SirYwell approved these changes

2023-07-10 21:15 UTC, NotMyFault approved these changes

2023-07-10 21:16 UTC, merged