fix: fixed history rollback
IntellectualSites/FastAsyncWorldEdit pull request #2367
Opened 2023-07-19 22:09 UTC by dordsor21

- Actual issue is settings the editsession changeset to the changeset we're undoing...?!?! And so we start abirtrarily overriding the history we want to do and completely and and utterly fucking everything. Please let's not do that again. Thanks :)
 - Also go ahead and clean up other parts of this, with more appropriate operators used
 - Fixes #2366

2023-07-25 18:38 UTC, SirYwell requested changes

2023-07-25 18:38 UTC, SirYwell commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/history/DiskStorageHistory.java
> +            System.out.println("CLOSING");
Leftover?

2023-07-25 18:38 UTC, SirYwell commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/HistorySubCommands.java
> +        BlockVector3 bot  = origin.toBlockPoint().subtract(radius, radius, radius);
```suggestion
        BlockVector3 bot = origin.toBlockPoint().subtract(radius, radius, radius);
```

2023-07-25 18:38 UTC, SirYwell commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/database/RollbackDatabase.java
> +                String stmtStr = ascending
Can we use if-else here and probably also text blocks?

2023-09-30 19:00 UTC, SirYwell approved these changes

2023-11-25 19:02 UTC, NotMyFault approved these changes

2023-11-25 20:32 UTC, merged