chore: warn when both history db and delete disk on logout are enabled
IntellectualSites/FastAsyncWorldEdit pull request #2824
Opened 2024-07-03 16:12 UTC by dordsor21

2024-07-05 08:31 UTC, SirYwell requested changes

2024-07-05 08:31 UTC, SirYwell commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/Fawe.java
> +            LOGGER.warn("!!!    logs out, recommended to disable delete-disk-on-logout if    !!!");
`logs logs`

2024-07-05 08:31 UTC, SirYwell commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/Fawe.java
> +            LOGGER.warn("!!!    Disable use-database if you want do not mind not having      !!!");
`want` sounds odd here?

2024-07-06 10:21 UTC, NotMyFault approved these changes

2024-08-25 14:02 UTC, SirYwell approved these changes

2024-08-25 14:20 UTC, merged