fix: use a holder to allow "upgrading" LocalBV3Set to a full fat one
IntellectualSites/FastAsyncWorldEdit pull request #3051
Opened 2024-12-30 17:39 UTC by dordsor21

There was a/some issue(s) that were due to a local set being used assumptively. The only instances of the local sets being explicitly used should now only be when using chunk coords, or for the floating tree remover

2024-12-31 08:38 UTC, SirYwell commented
Do we need to expose `BlockVector3SetHolder`? I think having a private/package-private class would be better, with static factory methods like `BlockVector3Set.expandable()` and `BlockVector3Set.fromLocal(LocalBlockVectorSet)` or something similar.

Also the `Cloneable` interface/the `clone()` method are kinda flawed, maybe it's better to just have our own `copy()` methods.

2024-12-31 10:34 UTC, dordsor21 commented
> Do we need to expose `BlockVector3SetHolder`? I think having a private/package-private class would be better, with static factory methods like `BlockVector3Set.expandable()` and `BlockVector3Set.fromLocal(LocalBlockVectorSet)` or something similar.
> 
> Also the `Cloneable` interface/the `clone()` method are kinda flawed, maybe it's better to just have our own `copy()` methods.

Yeah I can probably move it into the local directly as there's no reason to have a holder for a full fat bv3set.

I also just copied the fact the local already had a clone method tbh, but yeah copy would also be consistent with everything else in FAWE

2025-01-01 17:14 UTC, SirYwell requested changes

2025-01-01 17:14 UTC, SirYwell commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/math/LocalBlockVectorSet.java
> +    public static BlockVector3Set wrapped(int x, int z) {
The offset isn't used in any way, what's the intention here?

2025-01-01 17:14 UTC, SirYwell commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/math/BlockVectorSet.java
> +                .collect(Collectors.toMap(Long2ObjectMap.Entry::getLongKey, e -> (LocalBlockVectorSet) e.getValue().clone())));
This should use the copy method I guess?

2025-01-01 17:14 UTC, SirYwell commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/util/collection/BlockVector3Set.java
> +public interface BlockVector3Set extends Set<BlockVector3>, Cloneable {
`Cloneable` should be unneeded here now?

2025-01-03 14:25 UTC, dordsor21 commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/math/LocalBlockVectorSet.java
> +    public static BlockVector3Set wrapped(int x, int z) {
Had meant to pass it onto the localbv3set

2025-01-08 14:36 UTC, SirYwell commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/math/BlockVectorSet.java
> +            if ((offsetX & 2048) != 0 && (offsetY & 512) != 0 && (offsetZ & 2048) != 0) { // Can plug and play
I think I'm looking at this the third time and still questioning my sanity. But I assume this is supposed to check whether the localSet is already (2048, 512, 2048)-aligned? In that case, it would need to be `& 2047 == 0` etc. Otherwise I need an explanation because I can't wrap my head around it.

2025-01-08 14:38 UTC, dordsor21 commented on worldedit-core/src/main/java/com/fastasyncworldedit/core/math/BlockVectorSet.java
> +            if ((offsetX & 2048) != 0 && (offsetY & 512) != 0 && (offsetZ & 2048) != 0) { // Can plug and play
No you're right, I wasn't really thinking when I wrote this. I had meant to come back to look again but forgot and just committed

2025-01-08 16:54 UTC, SirYwell reviewed
I also noticed `CachedMask` catches `UnsupportedOperationException`, should that be adjusted too? I guess those try-catch blocks can just be removed this way?

2025-01-10 14:43 UTC, SirYwell approved these changes
Looks good

2025-01-18 16:41 UTC, NotMyFault approved these changes

2025-01-18 17:56 UTC, merged