Allow parallelisation of masks
IntellectualSites/FastAsyncWorldEdit pull request #636
Opened 2020-09-19 14:57 UTC by dordsor21

tested and seems to work fine so ¯\_(ツ)_/¯

2020-09-19 14:58 UTC, dordsor21 commented
![image](https://user-images.githubusercontent.com/10080017/93670146-e99f7e80-fa90-11ea-96f4-dfc042b77689.png)
nice

2020-09-19 15:28 UTC, aurorasmiles commented
What does this actually do? xD

2020-09-19 15:33 UTC, dordsor21 commented
The main point of it is this:
https://github.com/IntellectualSites/FastAsyncWorldEdit/pull/636/files#diff-bf597b58c1af88ba4850af6ae9fd27a7L103-L108

It had to be synchronised because a lot of masks are not thread safe. With this PR, masks are cloneable so we can have one mask per thread to account for this.

2020-09-20 14:39 UTC, N0tMyFaultOG approved these changes

2020-09-20 14:56 UTC, SirYwell reviewed
I don't like the usage of `Object#clone` here, as the implementations violate the javadocs of the clone method (`x.clone() != x` might be false). I'd prefer something similar to the `Filter#fork` method or just `copy()` (don't know why Mask2D has `copy` and `Mask` has `clone`

2020-09-20 14:58 UTC, dordsor21 commented
> I don't like the usage of `Object#clone` here, as the implementations violate the javadocs of the clone method (`x.clone() != x` might be false). I'd prefer something similar to the `Filter#fork` method or just `copy()` (don't know why Mask2D has `copy` and `Mask` has `clone`

They had to be different because AlwaysTrue and AlwaysFalse implement both Mask and Mask2D

2020-09-22 14:36 UTC, MattBDev requested changes

2020-09-22 14:36 UTC, MattBDev commented on worldedit-core/src/main/java/com/boydti/fawe/object/brush/mask/ImageBrushMask.java
> +    private final int cz;
please rename to chunkX, chunkY, chunkZ

2020-09-22 14:36 UTC, MattBDev commented on worldedit-core/src/main/java/com/boydti/fawe/object/brush/mask/ImageBrushMask.java
> +                          int cz,
chunkX, chunkY, chunkZ

2020-09-22 14:36 UTC, MattBDev commented on worldedit-core/src/main/java/com/boydti/fawe/object/brush/mask/ImageBrushMask.java
> +    @Override public boolean test(BlockVector3 vector) {
`@Override` should be on its own line.

2020-09-22 14:36 UTC, MattBDev commented on worldedit-core/src/main/java/com/boydti/fawe/object/brush/mask/ImageBrushMask.java
> +    @Override public Mask clone() {
`@Override` should be on its own line.

2020-09-22 14:36 UTC, MattBDev commented on worldedit-core/src/main/java/com/boydti/fawe/object/brush/mask/LayerBrushMask.java
> +    @Override public boolean test(BlockVector3 pos) {
`@Override` should be on its own line.

2020-09-22 14:36 UTC, MattBDev commented on worldedit-core/src/main/java/com/boydti/fawe/object/brush/mask/StencilBrushMask.java
> +    private final int cz;
chunkX, chunkY, chunkZ

2020-09-22 14:36 UTC, MattBDev commented on worldedit-core/src/main/java/com/boydti/fawe/object/brush/mask/StencilBrushMask.java
> +                            int cz,
chunkX, chunkY, chunkZ

2020-09-22 14:36 UTC, MattBDev commented on worldedit-core/src/main/java/com/boydti/fawe/object/brush/mask/StencilBrushMask.java
> +    @Override public Mask clone() {
`@Override` should be on its own line.

2020-09-22 14:36 UTC, MattBDev commented on worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/Masks.java
> +            @Override public Mask clone() {
`@Override` should be on its own line.

2020-09-22 14:36 UTC, MattBDev commented on worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/Masks.java
> +        @Override public Mask clone() {
`@Override` should be on its own line.

2020-09-22 14:36 UTC, MattBDev commented on worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/Masks.java
> +        @Override public Mask2D copy() {
`@Override` should be on its own line.

2020-09-22 14:36 UTC, MattBDev commented on worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/Masks.java
> +            @Override public Mask2D copy() {
`@Override` should be on its own line.

2020-09-22 14:36 UTC, MattBDev commented on worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/Masks.java
> +        @Override public Mask clone() {
`@Override` should be on its own line.

2020-09-22 14:36 UTC, MattBDev commented on worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/Masks.java
> +        @Override public Mask2D copy() {
`@Override` should be on its own line.

2020-09-22 14:36 UTC, MattBDev commented on worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/WallMakeMask.java
> +    @Override public boolean test(BlockVector3 position) {
`@Override` should be on its own line.

2020-09-22 14:36 UTC, MattBDev commented on worldedit-core/src/main/java/com/sk89q/worldedit/function/mask/WallMakeMask.java
> +    @Override public Mask clone() {
`@Override` should be on its own line.

2020-09-24 17:23 UTC, aurorasmiles approved these changes

2020-09-25 14:00 UTC, merged