Fix //jumpto
IntellectualSites/FastAsyncWorldEdit pull request #689
Opened 2020-10-07 16:09 UTC by weaondara

## Overview
added location argument parser

**Fixes #548**

## Description
added location argument parser

## Checklist

- [x] I included all information required in the sections above
- [x] I tested my changes and approved their functionality
- [x] I ensured my changes do not break other parts of the code
- [x] I read and followed the [contribution guidelines](https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/1.16/CONTRIBUTING.md)

2020-10-07 16:21 UTC, SirYwell requested changes
Besides the minor checkstyle stuff:
I think it might be worth to have the world as an optional parameter, don't know what you and the others think about that.

2020-10-07 16:21 UTC, SirYwell commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/argument/LocationConverter.java
> +        if (input.contains(","))
Missing braces

2020-10-07 16:21 UTC, SirYwell commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/argument/LocationConverter.java
> +        if (!world.isSuccessful())
Missing braces

2020-10-07 16:21 UTC, SirYwell commented on worldedit-core/src/main/java/com/sk89q/worldedit/command/argument/LocationConverter.java
> +        if (!vector.isSuccessful())
Missing braces

2020-10-07 16:34 UTC, MattBDev approved these changes
Address the issue with the if statement braces and it will be ready to be merged.

2020-10-07 17:05 UTC, aurorasmiles approved these changes

2020-10-08 07:17 UTC, N0tMyFaultOG approved these changes

2020-10-08 15:38 UTC, merged